name: "Env Replace"
description: "Change environment variables during actions"
branding:
  icon: "settings"
  color: "blue"
inputs:
  key:
    description: "env key"
    required: false
  value:
    description: "env value"
    required: false
  file:
    description: "env file path"
    required: false
    default: ".env"
  match-secrets:
    description: "match actions secrets"
    required: false
    default: "false"
  secrets:
    description: "secrets"
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
