name: "test"

on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          key: "HELLO"
          value: "TEST"
          file: "./src/tests/.env"
      - run: |
          cat ./src/tests/.env | grep "TEST"
  test-match-secrets:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          replace-all: |
            NEW=VALUE
          file: "./src/tests/.env"
          upsert: true
          remove-non-matches: true
      - run: |
          cat ./src/tests/.env | grep "VALUE"
